### ISSUE TITLE
new srp6 implementation

### ISSUE THREAD

**Issue by mc2programmer** [MariusTBjercke/BlizzlikeCMS#3]
For Trinitycore you will no longer be able to use sha_pass_hash. You will need to create a "salt" and a "verification" to register new users. You will also need to change the way you do verification for login. See Trinitycore website for documentation. also just look at a new Trinitycore auth|account fields for help.

**Comment by MariusTBjercke** [comment]
Thank you so much for the info! I just added a bugfix for this.
